### PR TITLE
Tracking and Analytics in Expo iPad app

### PR DESCRIPTION
**Pull request by yaolin902**
- Set up Firebase for analytics
- Configure Expo with Firebase credentials and package dependencies
- Configure EAS experimental build
To build: `eas build -p ios --profile development --local`

Advice to not merge to main branch yet as Expo Go does not support react-native-firebase/app.
Use this branch to add additional analytics as more features are developed

### CODE REVIEW

**Comment by yaolin902** [comment]
Additional analytics methods: https://rnfirebase.io/reference/analytics
Additional package requirement: `@react-native-firebase/app`, `@react-native-firebase/analytics`, `expo-build-properties`, and `expo-dev-client`, `eas-cli`. 
System packages: `fastlane`, `cocoapods`. 
A couple of commands to run before build are: `npx expo-doctor`

**Comment by yaolin902** [comment]
Added Privacy Policy screen with the ability to turn off data collection
Stores user's privacy preference using Async Storage

**Comment by yaolin902** [comment]
To build pure .ipa format without expo dev client.
Use this command: `npx expo prebuild --clean -p ios`
Requires Apple Developer account

**Comment by yaolin902** [comment]
Make sure to open `AwesomeProject.xcworkspace` instead of `AwesomeProject.xcodeproj`.
Go to `Product` -> `Clearn Build Folder...`, then `Product` -> `Archive`.
After build, go to `Distrubute App` -> `Custom` -> `Debugging`, then keep clicking `Next` until you see `Export` page.

**Review by argus1 — APPROVED** [review]

**Comment by yaolin902** [comment]
@argus1 major merge conflict, may hold the PR

**Comment by yaolin902** [comment]
[expo-firebase conflict (8)](https://trello.com/c/Qaf4JmyR/1-expo-firebase-conflict-8)

**Pull request merged**
